### ISSUE TITLE
request: add git package to docker image to allow requirements.txt file with git url's to work

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow-worker#14]
**Description**

I need to be able to install some private python modules. pip has an easy option for this but it requires git to be available via cli to clone the package.
This does make me wonder should it be possible to run an apt update and apt install of additional required packages set in an env var? workers need to be quite flexible so that may be a good thing to have.

**Steps to reproduce the issue:**

1. add a pip git uri to the requirements.txt file (set this file as part of env vars)
2. start docker image
3. error logs from container about git not being available

**Describe the results you received:**

```
airflow-worker_1  | airflow-worker 11:28:30.90
airflow-worker_1  | airflow-worker 11:28:30.91 Welcome to the Bitnami airflow-worker container
airflow-worker_1  | airflow-worker 11:28:30.91 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
airflow-worker_1  | airflow-worker 11:28:30.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues
airflow-worker_1  | airflow-worker 11:28:30.91
airflow-worker_1  | airflow-worker 11:28:30.92 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-worker_1  | WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
airflow-worker_1  | Collecting pyTitanEmail
airflow-worker_1  |   Cloning git://<obfuscated> to /tmp/pip-install-ajeo06i_/pytitanemail_abd0c6a2dab74164aa8d3868ebff8b07
airflow-worker_1  |   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q git://<obfuscated> /tmp/pip-install-ajeo06i_/pytitanemail_abd0c6a2dab74164aa8d3868ebff8b07
airflow-worker_1  | ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
airflow-worker_1  | WARNING: You are using pip version 20.3.1; however, version 21.2.4 is available.
airflow-worker_1  | You should consider upgrading via the '/opt/bitnami/airflow/venv/bin/python -m pip install --upgrade pip' command.
airflow-worker_1  | airflow-worker 11:28:33.41
```

**Describe the results you expected:**

pip to install all required packages successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

example requirements.txt line
`git+git://github.com/tangentlabs/django-oscar.git#egg=django-oscar`
**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

ubuntu vms. using docker-compose and haproxy as a frontend / loadbalancer

**Comment by juan131** [comment]
Hi @ITJamie 

In the [Airflow Helm chart](https://github.com/bitnami/charts/blob/master/bitnami/airflow], our solution for Kubernetes, we solved this by adding an init container (including git) that clones the custom DAG(s) and then share them with the worker container. Find more information in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/airflow#load-dag-files

Don't you think it'd be nice to use a similar approach using DockerCompose? Sth like this:

```yaml
version: '2'

services:
  dag-cloner:
    image: docker.io/bitnami/git:2
    command:
      - git clone https://github.com/USERNAME/REPOSITORY --branch master /dags || true
    volumes:
      - 'dags_data:/dags'
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - dags_data:/opt/bitnami/airflow/dags/
    depends_on:
      - postgresql
      - redis
      - dag-cloner
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - dags_data:/opt/bitnami/airflow/dags/
    depends_on:
      - postgresql
      - redis
      - dag-cloner
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - dags_data:/opt/bitnami/airflow/dags/
    depends_on:
      - postgresql
      - redis
      - dag-cloner

volumes:
  dags_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```

> Remember to replace `https://github.com/USERNAME/REPOSITORY` with the actual repo you want to clone
